sudo: required
language: python
services:
- docker
env:
  global:
  - IMAGE_NAME=haomingyin/script.ddns-cloudflare
  - DDNS_PROFILE=default
  # env as secrets: DOCKER_USERNAME, DOCKER_PASSWORD, X_AUTH_EMAIL, X_AUTH_KEY

before_install: []
install: []

before_script: []
script:
  - docker build --pull --tag "$IMAGE_NAME" .
after_script:
  - docker images

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_BUILD_NUMBER}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_BUILD_NUMBER}"
  on:
    branch: master