default:
  interval: 10 # in seconds
  records:
    - zone_name: "haomingyin.com"
      record_type: "A"
      name: "*.haomingyin.com"
ghost:
  interval: 180
  records:
    - zone_name: "haomingyin.com"
      record_type: "A"
      name: "ghost"
    - zone_name: "haomingyin.com"
      record_type: "A"
      name: "haomingyin.com"
      proxied: true
test:
  interval: 20
  records:
    - zone_name: "haomingyin.com"
      record_type: "TXT"
      name: "ddns-test.haomingyin.com"
      content: "test txt record"
    - zone_name: "haomingyin.com"
      record_type: "A"
      name: "test"
iaceit:
  interval: 180
  records:
    - zone_name: "iaceit.com"
      record_type: "A"
      name: "quiz"
      proxied: true
