default:
  interval: 180 # in seconds
  records:
    - zone_name: "haomingyin.com"
      record_type: "A"
      name: "*.haomingyin.com"
ghost:
  interval: 60
  records:
    - zone_name: "haomingyin.com"
      record_type: "A"
      name: "ghost"
test:
  interval: 20
  records:
    - zone_name: "haomingyin.com"
      record_type: "TXT"
      name: "ddns-test.haomingyin.com"
      content: "test txt record"
    - zone_name: "haomingyin.com"
      record_type: "A"
      name: "test"
